### PR TITLE
fix compat and adapt for ezdfsfile_cache table

### PR DESCRIPTION
**Pull request by Opencontent**
Add applyServerUrl method and change all table calls.
In _store and in _storeContents fix missing return statement.

### CODE REVIEW

**Comment by bdunogier** [comment]
Okay, _that_ is cool. Bravo.

The code seems fine to me. How well was this tested ? ;)

It'd have to pass some testing of course, but i'd be +1 on this.

**Comment by francescor** [comment]
any updates on this?

**Comment by yannickroger** [comment]
@francescor let's ping @Opencontent

**Comment by francescor** [comment]
yes @yannickroger, I work with Opencontent.
This pull request has been in production since then (code is fine, but we are working on performance now).
I was just wandering if somebody else have been using this code.

**Comment by andrerom** [comment]
+1

**Comment by yannickroger** [comment]
+1, Thanks @Opencontent

**Pull request merged**
